// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto.event;

public interface EventListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsr.event.EventList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dsr.event.IndexedEvent events = 1;</code>
   */
  java.util.List<IndexedEvent>
      getEventsList();
  /**
   * <code>repeated .dsr.event.IndexedEvent events = 1;</code>
   */
  IndexedEvent getEvents(int index);
  /**
   * <code>repeated .dsr.event.IndexedEvent events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .dsr.event.IndexedEvent events = 1;</code>
   */
  java.util.List<? extends IndexedEventOrBuilder>
      getEventsOrBuilderList();
  /**
   * <code>repeated .dsr.event.IndexedEvent events = 1;</code>
   */
  IndexedEventOrBuilder getEventsOrBuilder(
      int index);
}
