// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto.event;

public interface EventInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsr.event.EventInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_name = 1;</code>
   */
  String getEventName();
  /**
   * <code>string event_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string event_date = 2;</code>
   */
  String getEventDate();
  /**
   * <code>string event_date = 2;</code>
   */
  com.google.protobuf.ByteString
      getEventDateBytes();

  /**
   * <code>int32 start_time = 3;</code>
   */
  int getStartTime();

  /**
   * <code>int32 end_time = 4;</code>
   */
  int getEndTime();

  /**
   * <code>string location = 5;</code>
   */
  String getLocation();
  /**
   * <code>string location = 5;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
