// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto.event;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsr_event_EventInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsr_event_EventInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsr_event_IndexedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsr_event_IndexedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsr_event_EventId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsr_event_EventId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsr_event_EventList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsr_event_EventList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013event.proto\022\tdsr.event\032\033google/protobu" +
      "f/empty.proto\"k\n\tEventInfo\022\022\n\nevent_name" +
      "\030\001 \001(\t\022\022\n\nevent_date\030\002 \001(\t\022\022\n\nstart_time" +
      "\030\003 \001(\005\022\020\n\010end_time\030\004 \001(\005\022\020\n\010location\030\005 \001" +
      "(\t\"\\\n\014IndexedEvent\022#\n\007eventId\030\001 \001(\0132\022.ds" +
      "r.event.EventId\022\'\n\teventInfo\030\002 \001(\0132\024.dsr" +
      ".event.EventInfo\"\033\n\007EventId\022\020\n\010event_id\030" +
      "\001 \001(\005\"4\n\tEventList\022\'\n\006events\030\001 \003(\0132\027.dsr" +
      ".event.IndexedEvent2\306\002\n\014EventService\0229\n\013" +
      "createEvent\022\024.dsr.event.EventInfo\032\022.dsr." +
      "event.EventId\"\000\022>\n\rretrieveEvent\022\022.dsr.e" +
      "vent.EventId\032\027.dsr.event.IndexedEvent\"\000\022" +
      "@\n\013updateEvent\022\027.dsr.event.IndexedEvent\032" +
      "\026.google.protobuf.Empty\"\000\022;\n\013deleteEvent" +
      "\022\022.dsr.event.EventId\032\026.google.protobuf.E" +
      "mpty\"\000\022<\n\nlistEvents\022\026.google.protobuf.E" +
      "mpty\032\024.dsr.event.EventList\"\000B(\n$dk.dsrho" +
      "rsens.volunteers.proto.eventP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_dsr_event_EventInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dsr_event_EventInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsr_event_EventInfo_descriptor,
        new String[] { "EventName", "EventDate", "StartTime", "EndTime", "Location", });
    internal_static_dsr_event_IndexedEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dsr_event_IndexedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsr_event_IndexedEvent_descriptor,
        new String[] { "EventId", "EventInfo", });
    internal_static_dsr_event_EventId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dsr_event_EventId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsr_event_EventId_descriptor,
        new String[] { "EventId", });
    internal_static_dsr_event_EventList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dsr_event_EventList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsr_event_EventList_descriptor,
        new String[] { "Events", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
