// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto.event;

public interface EventIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsr.event.EventId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 event_id = 1;</code>
   */
  int getEventId();
}
