// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto.event;

public interface IndexedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsr.event.IndexedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dsr.event.EventId eventId = 1;</code>
   */
  boolean hasEventId();
  /**
   * <code>.dsr.event.EventId eventId = 1;</code>
   */
  EventId getEventId();
  /**
   * <code>.dsr.event.EventId eventId = 1;</code>
   */
  EventIdOrBuilder getEventIdOrBuilder();

  /**
   * <code>.dsr.event.EventInfo eventInfo = 2;</code>
   */
  boolean hasEventInfo();
  /**
   * <code>.dsr.event.EventInfo eventInfo = 2;</code>
   */
  EventInfo getEventInfo();
  /**
   * <code>.dsr.event.EventInfo eventInfo = 2;</code>
   */
  EventInfoOrBuilder getEventInfoOrBuilder();
}
