// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:volunteer_manager.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventName = 2;</code>
   */
  java.lang.String getEventName();
  /**
   * <code>string eventName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string eventTimestamp = 3;</code>
   */
  java.lang.String getEventTimestamp();
  /**
   * <code>string eventTimestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getEventTimestampBytes();
}
