// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public interface EventListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:volunteer_manager.EventList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse> 
      getEventsList();
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  dk.dsrhorsens.volunteers.proto.EventResponse getEvents(int index);
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  java.util.List<? extends dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder getEventsOrBuilder(
      int index);
}
