// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public interface EventIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:volunteer_manager.EventId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
