// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_volunteer_manager_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_volunteer_manager_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_volunteer_manager_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_volunteer_manager_EventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_volunteer_manager_EventId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_volunteer_manager_EventId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_volunteer_manager_OperationStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_volunteer_manager_OperationStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_volunteer_manager_EventList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_volunteer_manager_EventList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\021volunteer_manager\"9\n\014Even" +
      "tRequest\022\021\n\teventName\030\002 \001(\t\022\026\n\016eventTime" +
      "stamp\030\003 \001(\t\"g\n\rEventResponse\022+\n\007eventId\030" +
      "\001 \001(\0132\032.volunteer_manager.EventId\022\021\n\teve" +
      "ntName\030\002 \001(\t\022\026\n\016eventTimestamp\030\003 \001(\t\"\025\n\007" +
      "EventId\022\n\n\002id\030\001 \001(\005\"\"\n\017OperationStatus\022\017" +
      "\n\007success\030\001 \001(\010\"=\n\tEventList\0220\n\006events\030\001" +
      " \003(\0132 .volunteer_manager.EventResponse2\315" +
      "\002\n\005Event\022L\n\013createEvent\022\037.volunteer_mana" +
      "ger.EventRequest\032\032.volunteer_manager.Eve",
      "ntId\"\000\022O\n\rretrieveEvent\022\032.volunteer_mana" +
      "ger.EventId\032 .volunteer_manager.EventRes" +
      "ponse\"\000\022T\n\013updateEvent\022\037.volunteer_manag" +
      "er.EventRequest\032\".volunteer_manager.Oper" +
      "ationStatus\"\000\022O\n\013deleteEvent\022\032.volunteer" +
      "_manager.EventId\032\".volunteer_manager.Ope" +
      "rationStatus\"\000B\"\n\036dk.dsrhorsens.voluntee" +
      "rs.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_volunteer_manager_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_volunteer_manager_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_volunteer_manager_EventRequest_descriptor,
        new java.lang.String[] { "EventName", "EventTimestamp", });
    internal_static_volunteer_manager_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_volunteer_manager_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_volunteer_manager_EventResponse_descriptor,
        new java.lang.String[] { "EventId", "EventName", "EventTimestamp", });
    internal_static_volunteer_manager_EventId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_volunteer_manager_EventId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_volunteer_manager_EventId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_volunteer_manager_OperationStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_volunteer_manager_OperationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_volunteer_manager_OperationStatus_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_volunteer_manager_EventList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_volunteer_manager_EventList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_volunteer_manager_EventList_descriptor,
        new java.lang.String[] { "Events", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
