// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

/**
 * Protobuf type {@code volunteer_manager.EventList}
 */
public  final class EventList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:volunteer_manager.EventList)
    EventListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventList.newBuilder() to construct.
  private EventList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventList() {
    events_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EventList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              events_ = new java.util.ArrayList<dk.dsrhorsens.volunteers.proto.EventResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            events_.add(
                input.readMessage(dk.dsrhorsens.volunteers.proto.EventResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        events_ = java.util.Collections.unmodifiableList(events_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.dsrhorsens.volunteers.proto.EventOuterClass.internal_static_volunteer_manager_EventList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.dsrhorsens.volunteers.proto.EventOuterClass.internal_static_volunteer_manager_EventList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.dsrhorsens.volunteers.proto.EventList.class, dk.dsrhorsens.volunteers.proto.EventList.Builder.class);
  }

  public static final int EVENTS_FIELD_NUMBER = 1;
  private java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse> events_;
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  public java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse> getEventsList() {
    return events_;
  }
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  public java.util.List<? extends dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder> 
      getEventsOrBuilderList() {
    return events_;
  }
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  public dk.dsrhorsens.volunteers.proto.EventResponse getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
   */
  public dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder getEventsOrBuilder(
      int index) {
    return events_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < events_.size(); i++) {
      output.writeMessage(1, events_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < events_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, events_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.dsrhorsens.volunteers.proto.EventList)) {
      return super.equals(obj);
    }
    dk.dsrhorsens.volunteers.proto.EventList other = (dk.dsrhorsens.volunteers.proto.EventList) obj;

    boolean result = true;
    result = result && getEventsList()
        .equals(other.getEventsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.dsrhorsens.volunteers.proto.EventList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.dsrhorsens.volunteers.proto.EventList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code volunteer_manager.EventList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:volunteer_manager.EventList)
      dk.dsrhorsens.volunteers.proto.EventListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.dsrhorsens.volunteers.proto.EventOuterClass.internal_static_volunteer_manager_EventList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.dsrhorsens.volunteers.proto.EventOuterClass.internal_static_volunteer_manager_EventList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.dsrhorsens.volunteers.proto.EventList.class, dk.dsrhorsens.volunteers.proto.EventList.Builder.class);
    }

    // Construct using dk.dsrhorsens.volunteers.proto.EventList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEventsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.dsrhorsens.volunteers.proto.EventOuterClass.internal_static_volunteer_manager_EventList_descriptor;
    }

    public dk.dsrhorsens.volunteers.proto.EventList getDefaultInstanceForType() {
      return dk.dsrhorsens.volunteers.proto.EventList.getDefaultInstance();
    }

    public dk.dsrhorsens.volunteers.proto.EventList build() {
      dk.dsrhorsens.volunteers.proto.EventList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public dk.dsrhorsens.volunteers.proto.EventList buildPartial() {
      dk.dsrhorsens.volunteers.proto.EventList result = new dk.dsrhorsens.volunteers.proto.EventList(this);
      int from_bitField0_ = bitField0_;
      if (eventsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.events_ = events_;
      } else {
        result.events_ = eventsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.dsrhorsens.volunteers.proto.EventList) {
        return mergeFrom((dk.dsrhorsens.volunteers.proto.EventList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.dsrhorsens.volunteers.proto.EventList other) {
      if (other == dk.dsrhorsens.volunteers.proto.EventList.getDefaultInstance()) return this;
      if (eventsBuilder_ == null) {
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
      } else {
        if (!other.events_.isEmpty()) {
          if (eventsBuilder_.isEmpty()) {
            eventsBuilder_.dispose();
            eventsBuilder_ = null;
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000001);
            eventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventsFieldBuilder() : null;
          } else {
            eventsBuilder_.addAllMessages(other.events_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.dsrhorsens.volunteers.proto.EventList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.dsrhorsens.volunteers.proto.EventList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse> events_ =
      java.util.Collections.emptyList();
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        events_ = new java.util.ArrayList<dk.dsrhorsens.volunteers.proto.EventResponse>(events_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.dsrhorsens.volunteers.proto.EventResponse, dk.dsrhorsens.volunteers.proto.EventResponse.Builder, dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder> eventsBuilder_;

    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse> getEventsList() {
      if (eventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(events_);
      } else {
        return eventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public int getEventsCount() {
      if (eventsBuilder_ == null) {
        return events_.size();
      } else {
        return eventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public dk.dsrhorsens.volunteers.proto.EventResponse getEvents(int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);
      } else {
        return eventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder setEvents(
        int index, dk.dsrhorsens.volunteers.proto.EventResponse value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder setEvents(
        int index, dk.dsrhorsens.volunteers.proto.EventResponse.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder addEvents(dk.dsrhorsens.volunteers.proto.EventResponse value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder addEvents(
        int index, dk.dsrhorsens.volunteers.proto.EventResponse value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(index, value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder addEvents(
        dk.dsrhorsens.volunteers.proto.EventResponse.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder addEvents(
        int index, dk.dsrhorsens.volunteers.proto.EventResponse.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder addAllEvents(
        java.lang.Iterable<? extends dk.dsrhorsens.volunteers.proto.EventResponse> values) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
      } else {
        eventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder clearEvents() {
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public Builder removeEvents(int index) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.remove(index);
        onChanged();
      } else {
        eventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public dk.dsrhorsens.volunteers.proto.EventResponse.Builder getEventsBuilder(
        int index) {
      return getEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder getEventsOrBuilder(
        int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);  } else {
        return eventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public java.util.List<? extends dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder> 
         getEventsOrBuilderList() {
      if (eventsBuilder_ != null) {
        return eventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(events_);
      }
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public dk.dsrhorsens.volunteers.proto.EventResponse.Builder addEventsBuilder() {
      return getEventsFieldBuilder().addBuilder(
          dk.dsrhorsens.volunteers.proto.EventResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public dk.dsrhorsens.volunteers.proto.EventResponse.Builder addEventsBuilder(
        int index) {
      return getEventsFieldBuilder().addBuilder(
          index, dk.dsrhorsens.volunteers.proto.EventResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .volunteer_manager.EventResponse events = 1;</code>
     */
    public java.util.List<dk.dsrhorsens.volunteers.proto.EventResponse.Builder> 
         getEventsBuilderList() {
      return getEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.dsrhorsens.volunteers.proto.EventResponse, dk.dsrhorsens.volunteers.proto.EventResponse.Builder, dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder> 
        getEventsFieldBuilder() {
      if (eventsBuilder_ == null) {
        eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.dsrhorsens.volunteers.proto.EventResponse, dk.dsrhorsens.volunteers.proto.EventResponse.Builder, dk.dsrhorsens.volunteers.proto.EventResponseOrBuilder>(
                events_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        events_ = null;
      }
      return eventsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:volunteer_manager.EventList)
  }

  // @@protoc_insertion_point(class_scope:volunteer_manager.EventList)
  private static final dk.dsrhorsens.volunteers.proto.EventList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.dsrhorsens.volunteers.proto.EventList();
  }

  public static dk.dsrhorsens.volunteers.proto.EventList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventList>
      PARSER = new com.google.protobuf.AbstractParser<EventList>() {
    public EventList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventList> getParserForType() {
    return PARSER;
  }

  public dk.dsrhorsens.volunteers.proto.EventList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

