// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:volunteer_manager.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.volunteer_manager.EventId eventId = 1;</code>
   */
  boolean hasEventId();
  /**
   * <code>.volunteer_manager.EventId eventId = 1;</code>
   */
  dk.dsrhorsens.volunteers.proto.EventId getEventId();
  /**
   * <code>.volunteer_manager.EventId eventId = 1;</code>
   */
  dk.dsrhorsens.volunteers.proto.EventIdOrBuilder getEventIdOrBuilder();

  /**
   * <code>string eventName = 2;</code>
   */
  java.lang.String getEventName();
  /**
   * <code>string eventName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string eventTimestamp = 3;</code>
   */
  java.lang.String getEventTimestamp();
  /**
   * <code>string eventTimestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getEventTimestampBytes();
}
