// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package dk.dsrhorsens.volunteers.proto;

public interface OperationStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:volunteer_manager.OperationStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
